spring:
  datasource:
    url: jdbc:postgresql://<host>:<port>/<database>
    username: <username>
    password: <password>
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false
  security:
    user:
      name: <name>
      password: <password>
      roles: [ "<role>" ]
