spring:
  datasource:
    url: jdbc:postgresql://<host>:<port>/<database>
    username: <username>
    password: <password>
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false
cors:
  origins: ["http://127.0.0.1:5173", "http://localhost:5173"]